/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminiRouteImport } from './routes/termini'
import { Route as SpaziRouteImport } from './routes/spazi'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GalleriaRouteImport } from './routes/galleria'
import { Route as EventiRouteImport } from './routes/eventi'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TerminiRoute = TerminiRouteImport.update({
  id: '/termini',
  path: '/termini',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaziRoute = SpaziRouteImport.update({
  id: '/spazi',
  path: '/spazi',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriaRoute = GalleriaRouteImport.update({
  id: '/galleria',
  path: '/galleria',
  getParentRoute: () => rootRouteImport,
} as any)
const EventiRoute = EventiRouteImport.update({
  id: '/eventi',
  path: '/eventi',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/eventi': typeof EventiRoute
  '/galleria': typeof GalleriaRoute
  '/privacy': typeof PrivacyRoute
  '/spazi': typeof SpaziRoute
  '/termini': typeof TerminiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/eventi': typeof EventiRoute
  '/galleria': typeof GalleriaRoute
  '/privacy': typeof PrivacyRoute
  '/spazi': typeof SpaziRoute
  '/termini': typeof TerminiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/eventi': typeof EventiRoute
  '/galleria': typeof GalleriaRoute
  '/privacy': typeof PrivacyRoute
  '/spazi': typeof SpaziRoute
  '/termini': typeof TerminiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/chi-siamo'
    | '/contatti'
    | '/cookie-policy'
    | '/eventi'
    | '/galleria'
    | '/privacy'
    | '/spazi'
    | '/termini'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/chi-siamo'
    | '/contatti'
    | '/cookie-policy'
    | '/eventi'
    | '/galleria'
    | '/privacy'
    | '/spazi'
    | '/termini'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/chi-siamo'
    | '/contatti'
    | '/cookie-policy'
    | '/eventi'
    | '/galleria'
    | '/privacy'
    | '/spazi'
    | '/termini'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ChiSiamoRoute: typeof ChiSiamoRoute
  ContattiRoute: typeof ContattiRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  EventiRoute: typeof EventiRoute
  GalleriaRoute: typeof GalleriaRoute
  PrivacyRoute: typeof PrivacyRoute
  SpaziRoute: typeof SpaziRoute
  TerminiRoute: typeof TerminiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termini': {
      id: '/termini'
      path: '/termini'
      fullPath: '/termini'
      preLoaderRoute: typeof TerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spazi': {
      id: '/spazi'
      path: '/spazi'
      fullPath: '/spazi'
      preLoaderRoute: typeof SpaziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleria': {
      id: '/galleria'
      path: '/galleria'
      fullPath: '/galleria'
      preLoaderRoute: typeof GalleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventi': {
      id: '/eventi'
      path: '/eventi'
      fullPath: '/eventi'
      preLoaderRoute: typeof EventiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ChiSiamoRoute: ChiSiamoRoute,
  ContattiRoute: ContattiRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  EventiRoute: EventiRoute,
  GalleriaRoute: GalleriaRoute,
  PrivacyRoute: PrivacyRoute,
  SpaziRoute: SpaziRoute,
  TerminiRoute: TerminiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
